Change interface paradigm to pure graph, and complete LCI and LCIA sections
brightway-lca/bw_interface_schemas pull request #12
Opened 2024-12-13 08:31 UTC by cmutel

2024-12-13 12:38 UTC, tngTUDOR commented on README.md
> +* Add attribute data is stored as JSON-serializable values.
typo (non-blocking): Maybe you meant "All" and not Add here.

2024-12-13 14:06 UTC, tngTUDOR requested changes
Technically speaking the move to one full Graph is ok for me.
As the code itself has it, changes are certainly expected.

I think the testing part could definitely be improved. asserting that the functions work fine is OK, but if we want make sure we don't introduce unwanted regressions when updating the schema above 0.2.X, we might want to have more detailed integration tests.

2024-12-13 14:06 UTC, tngTUDOR commented on dev/Example-graph.key
suggestion (blocking): If this file is not used anywhere else in the code, maybe it can be removed.

I wonder if it is the source for the PNG of the bike inventory.

2024-12-13 14:06 UTC, tngTUDOR commented on tests/integration.py
> +    assert bike_as_graph.model_dump()
suggestion (blocking): What about if we could test the result of the model_dump compared to the fixture ?

2024-12-13 14:06 UTC, tngTUDOR commented on tests/integration.py
> +    assert load_graph(bike_as_dict)
suggestion (blocking): we could verify that every node in the fixture is present in the Graph object created by the load_graph function, as well as the edges, as a deeper test.

2024-12-16 07:52 UTC, cmutel commented on dev/Example-graph.key
It is.

2024-12-19 08:38 UTC, tngTUDOR approved these changes
LGTM

2024-12-19 09:16 UTC, merged